In [1]:
import pandas as pd

In [3]:
df1 = pd.read_csv("archive/Results1.csv")

In [4]:
df1.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,"261,96",2,0,"41,9136"
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...","731,94",3,0,"219,582"
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,"14,62",2,0,"6,8714"
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,"957,5775",5,"0,45","-383,031"
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,"22,368",2,"0,2","2,5164"

In [76]:
df2 = df1[~df1.duplicated(subset=['Product_ID', 'Product_Name'], keep='first')]

In [93]:
df3 =  df2.groupby("Product_Name").agg({"Product_ID":"count"}).sort_values(by="Product_ID", ascending=False).reset_index()

In [94]:
df3.head(40)

                                         Product_Name  Product_ID
0                                             Staples          10
1                                     Staple envelope           9
2                                   Easy-staple paper           8
3                             Staples in misc. colors           7
4                                       Staple holder           3
5                                      Staple remover           3
6                            Prang Drawing Pencil Set           2
7                         Eldon Wave Desk Accessories           2
8                          KI Adjustable-Height Table           2
9       Peel & Seel Recycled Catalog Envelopes, Brown           2
10                            Storex Dura Pro Binders           2
11                                      Staple magnet           2
12                         Staple-based wall hangings           2
13                              Okidata C610n Printer           2
14            #10- 4 1/8" x 9 1/2" Recycled Envelopes           2
15                            Avery Non-Stick Binders           2
16          Panasonic KX MB2061 Multifunction Printer           1
17                               Panasonic KX-TG9471B           1
18                  Panasonic KX TS3282W Corded phone           1
19  Panasonic KX-TG6844B Expandable Digital Cordle...           1
20                  Panasonic KX TS3282B Corded phone           1
21                   Panasonic KX TS208W Corded phone           1
22                 Panasonic KX T7736-B Digital phone           1
23                 Panasonic KX T7731-B Digital phone           1
24  Panasonic KX MC6040 Color Laser Multifunction ...           1
25         Panasonic KP-150 Electric Pencil Sharpener           1
26                    Panasonic KX - TS880B Telephone           1
27  Panasonic KP-4ABK Battery-Operated Pencil Shar...           1
28  Panasonic KP-380BK Classic Electric Pencil Sha...           1
29  Panasonic KP-350BK Electric Pencil Sharpener w...           1
30  Panasonic KP-310 Heavy-Duty Electric Pencil Sh...           1
31                                 Panasonic Kx-TS550           1
32             Panasonic Businessï¿½Telephonesï¿½KX-T7736           1
33             Padded Folding Chairs, Black, 4/Carton           1
34                  PNY Rapid USB Car Charger - Black           1
35          OtterBox Defender Series Case - iPhone 5c           1
36  OtterBox Defender Series Case - Samsung Galaxy S4           1
37  Panasonic KX-TG9541B DECT 6.0 Digital 2-Line E...           1
38                 Peel & Stick Add-On Corner Pockets           1
39   Park Ridge Embossed Executive Business Envelopes           1

In [95]:
df3 = df3[df3["Product_ID"]> 1]

In [100]:
df3.head(10)

                                    Product_Name  Product_ID
0                                        Staples          10
1                                Staple envelope           9
2                              Easy-staple paper           8
3                        Staples in misc. colors           7
4                                  Staple holder           3
5                                 Staple remover           3
6                       Prang Drawing Pencil Set           2
7                    Eldon Wave Desk Accessories           2
8                     KI Adjustable-Height Table           2
9  Peel & Seel Recycled Catalog Envelopes, Brown           2

In [119]:
namelist = []
namelist = df3["Product_Name"]

In [140]:
df4 = df1[df1["Product_Name"].isin(df3["Product_Name"].values)]

In [141]:
df4 = df4[~df4.duplicated(subset=['Product_ID', 'Product_Name'], keep='first')]

In [149]:
df4.to_csv("df4.csv")

In [150]:
df4 = pd.read_excel("archive/Book1.xlsx", sheet_name="df4")

In [151]:
df4.head()

                         name               id
0     Storex Dura Pro Binders  OFF-BI-10001922
1     Staples in misc. colors  OFF-AR-10004707
2                     Staples  OFF-FA-10003485
3  Staple-based wall hangings  FUR-FU-10004351
4              Staple remover  OFF-SU-10000946

In [152]:
df4["ID"] = df4["id"].str[:4] + "AA" + df4["id"].str[-9:]

In [153]:
df4.head()

                         name               id               ID
0     Storex Dura Pro Binders  OFF-BI-10001922  OFF-AA-10001922
1     Staples in misc. colors  OFF-AR-10004707  OFF-AA-10004707
2                     Staples  OFF-FA-10003485  OFF-AA-10003485
3  Staple-based wall hangings  FUR-FU-10004351  FUR-AA-10004351
4              Staple remover  OFF-SU-10000946  OFF-AA-10000946

In [157]:
for i in range(0, len(df4.index)):
    product_name = df4["name"].iloc[i]
    mask = df1["Product_Name"] == product_name
    if mask.any():
        df1.loc[mask, 'Product_ID'] = df4["id"].iloc[i]

In [158]:
df1.to_csv("son1.3.csv")

In [201]:
df1 = pd.read_excel("archive/Book1.xlsx", sheet_name="son1.3")

In [202]:
df1.head()

,Column1,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,...,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
0,0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,26196,2,0,419136
1,1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",73194,3,0,219582
2,2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,1462,2,0,68714
3,3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,9575775,5,45,-383031
4,4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22368,2,2,25164

In [203]:
df2 = df1[~df1.duplicated(subset=['Product_ID', 'Product_Name'], keep='first')]

In [204]:
df3 =  df2.groupby("Product_ID").agg({"Product_Name":"count"}).sort_values(by="Product_Name", ascending=False).reset_index()

In [205]:
df3.head()

        Product_ID  Product_Name
0  TEC-AC-10003832             2
1  OFF-PA-10001970             2
2  TEC-PH-10002200             2
3  OFF-BI-10002026             2
4  OFF-PA-10000477             2

In [206]:
df3 = df3[df3["Product_Name"]> 1]

In [207]:
df3.head(50)

         Product_ID  Product_Name
0   TEC-AC-10003832             2
1   OFF-PA-10001970             2
2   TEC-PH-10002200             2
3   OFF-BI-10002026             2
4   OFF-PA-10000477             2
5   OFF-PA-10002195             2
6   OFF-BI-10004632             2
7   OFF-AR-10001149             2
8   OFF-BI-10004654             2
9   OFF-PA-10000357             2
10  FUR-FU-10004017             2
11  OFF-PA-10002377             2
12  FUR-FU-10004091             2
13  OFF-AP-10000576             2
14  FUR-FU-10004270             2
15  FUR-FU-10004864             2
16  FUR-CH-10001146             2
17  FUR-FU-10001473             2
18  FUR-FU-10004848             2
19  OFF-ST-10001228             2
20  TEC-AC-10002550             2
21  TEC-PH-10002310             2
22  TEC-MA-10001148             2
23  TEC-PH-10001795             2
24  OFF-PA-10003022             2
25  OFF-PA-10000659             2
26  OFF-ST-10004950             2
27  FUR-BO-10002213             2
28  TEC-PH-10001530             2
29  OFF-PA-10001166             2
30  TEC-AC-10002049             2
31  TEC-PH-10004531             2

In [208]:
df4 = df1[df1["Product_ID"].isin(df3["Product_ID"])]

In [209]:
df4.head()

,Column1,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,...,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
29,29,30,US-2015-150630,2015-09-17,2015-09-21,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,...,19140,East,FUR-FU-10004848,Furniture,Furnishings,"Howard Miller 13-3/4"" Diameter Brushed Chrome ...",1242,3,2,15525
66,66,67,US-2015-164175,2015-04-30,2015-05-05,Standard Class,PS-18970,Paul Stevenson,Home Office,United States,...,60610,Central,FUR-CH-10001146,Furniture,Chairs,"Global Value Mid-Back Manager's Chair, Gray",213115,5,3,-152225
70,70,71,CA-2016-106075,2016-09-18,2016-09-23,Standard Class,HM-14980,Henry MacAllister,Consumer,United States,...,10009,East,OFF-BI-10004654,Office Supplies,Binders,Avery Binding System Hidden Tab Executive Styl...,4616,1,2,1731
128,128,129,US-2016-125969,2016-11-06,2016-11-10,Second Class,LS-16975,Lindsay Shagiari,Home Office,United States,...,90004,West,FUR-CH-10001146,Furniture,Chairs,"Global Task Chair, Black",81424,2,2,-91602
131,131,132,US-2017-164147,2017-02-02,2017-02-05,First Class,DW-13585,Dorothy Wardle,Corporate,United States,...,43229,East,OFF-PA-10002377,Office Supplies,Paper,Xerox 1916,78304,2,2,29364

In [210]:
names = []
names = df4["Product_Name"].drop_duplicates()

In [211]:
type(names)

pandas.core.series.Series

In [212]:
names.to_csv("names.csv")

In [213]:
names = pd.read_excel("archive/Book1.xlsx", sheet_name="names")

In [214]:
names.head()

,Unnamed: 0,Product_Name,Porduct_ID
0,Column1,"Global Value Mid-Back Manager's Chair, Gray",FUR-AZ-10001146
1,29,"Global Task Chair, Black",FUR-AZ-10001146
2,66,DAX Wood Document Frame,FUR-AZ-10001473
3,70,"Eldon Executive Woodline II Desk Accessories, ...",FUR-AZ-10001473
4,128,DMI Eclipse Executive Suite Bookcases,FUR-AZ-10002213

In [215]:
for i in range(0, len(names.index)):
    product_name = names["Product_Name"].iloc[i]
    mask = df1["Product_Name"] == product_name
    if mask.any():
        df1.loc[mask, 'Product_ID'] = names["Porduct_ID"].iloc[i]

In [216]:
df1.head()

,Column1,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,...,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
0,0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,26196,2,0,419136
1,1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",73194,3,0,219582
2,2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,1462,2,0,68714
3,3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,9575775,5,45,-383031
4,4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22368,2,2,25164

In [218]:
df1.to_csv("son1.5.csv")

In [219]:
df1 = pd.read_excel("archive/Book1.xlsx", sheet_name="son1.5")

In [220]:
names = pd.read_excel("archive/Book1.xlsx", sheet_name="names")

In [222]:
names.head()

        Product_ID                                   Product_Name
0  TEC-AY-10002550                     Maxell 4.7GB DVD-RW 3/Pack
1  TEC-AY-10004531  OtterBox Commuter Series Case - iPhone 5 & 5s
2  TEC-AY-10003832             Logitechï¿½P710e Mobile Speakerphone
3  TEC-AY-10002200                          Samsung Galaxy Note 2
4  TEC-AY-10002310             Panasonic KX T7731-B Digital phone

In [223]:
for i in range(0, len(names.index)):
    product_name = names["Product_Name"].iloc[i]
    mask = df1["Product_Name"] == product_name
    if mask.any():
        df1.loc[mask, 'Product_ID'] = names["Product_ID"].iloc[i]

In [224]:
df1.to_csv("son1.6.csv")