In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_ = pd.read_csv("archive/superStoreDB.csv")
df = df_.copy()

In [3]:
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,"261,96",2,0,"41,9136"
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...","731,94",3,0,"219,582"
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,"14,62",2,0,"6,8714"
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,"957,5775",5,"0,45","-383,031"
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,"22,368",2,"0,2","2,5164"

In [4]:
df.tail()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,"25,248",3,"0,2","4,1028"
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,"91,96",2,0,"15,6332"
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,"258,576",2,"0,2","19,3932"
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""","29,6",4,0,"13,32"
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...","243,16",2,0,"72,948"

In [5]:
df.columns

Index(['Row_ID', 'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode',
       'Customer_ID', 'Customer_Name', 'Segment', 'Country', 'City', 'State',
       'Postal_Code', 'Region', 'Product_ID', 'Category', 'Sub_Category',
       'Product_Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [12]:
df.index

RangeIndex(start=0, stop=9994, step=1)

In [31]:
result = df.groupby(["Product_ID"]).agg({"Quantity":"sum"}).rename(columns={"Quantity": "quantity_sum"}).sort_values(by="quantity_sum", ascending=False).head().reset_index()
max_product_ID = result.iloc[0]['Product_ID']
[val for val in df[df["Product_ID"] == max_product_ID]["Order_ID"]]
select_order_ID = [val for val in df[df["Product_ID"] == max_product_ID]["Order_ID"].values]

In [35]:
result

        Product_ID  quantity_sum
0  TEC-AC-10003832            75
1  OFF-PA-10001970            70
2  OFF-BI-10001524            67
3  FUR-CH-10002647            64
4  OFF-BI-10002026            64

In [ ]:
[val for val in df[df["Product_ID"] == "OFF-PA-10001970"]["Order_ID"]]

In [37]:
[val for val in df[df["Product_ID"] == "OFF-PA-10001970"]["Order_ID"]]

['CA-2016-129714',
 'CA-2016-129714',
 'CA-2017-117457',
 'CA-2016-147375',
 'CA-2016-152814',
 'CA-2015-142755',
 'CA-2017-117212',
 'US-2017-129777',
 'CA-2015-142377',
 'CA-2016-119963',
 'CA-2015-105158',
 'CA-2014-133305',
 'CA-2017-102197',
 'CA-2017-124744',
 'CA-2015-156013',
 'CA-2015-121776',
 'CA-2017-156776',
 'US-2017-127292',
 'CA-2016-113607']

In [32]:
[col for col in select_order_ID]

['US-2017-100930',
 'CA-2016-145625',
 'US-2016-139486',
 'CA-2017-106103',
 'CA-2017-130351',
 'US-2017-132444',
 'CA-2016-105963',
 'CA-2016-111794',
 'CA-2016-134887',
 'CA-2014-127558',
 'CA-2016-133795',
 'US-2014-159618',
 'CA-2017-140872',
 'CA-2016-108224',
 'CA-2017-162015',
 'CA-2017-116988',
 'US-2015-115343',
 'CA-2016-129280']

In [33]:
df1 = df[df["Order_ID"].isin(select_order_ID)] #en Ã§ok satÄ±lan Ã¼rÃ¼nÃ¼n order_id leri

In [34]:
df1.head(10)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
231,232,US-2017-100930,4/7/2017,4/12/2017,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Tampa,...,33614,South,FUR-TA-10001705,Furniture,Tables,Bush Advantage Collection Round Conference Table,"233,86",2,"0,45","-102,048"
232,233,US-2017-100930,4/7/2017,4/12/2017,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Tampa,...,33614,South,FUR-TA-10003473,Furniture,Tables,Bretford Rectangular Conference Table Tops,"620,6145",3,"0,45","-248,2458"
233,234,US-2017-100930,4/7/2017,4/12/2017,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Tampa,...,33614,South,OFF-BI-10001679,Office Supplies,Binders,GBC Instant Index System for Binding Systems,"5,328",2,"0,7","-3,552"
234,235,US-2017-100930,4/7/2017,4/12/2017,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Tampa,...,33614,South,FUR-FU-10004017,Furniture,Furnishings,Tenex Contemporary Contur Chairmats for Low an...,"258,072",3,"0,2",0
235,236,US-2017-100930,4/7/2017,4/12/2017,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Tampa,...,33614,South,TEC-AC-10003832,Technology,Accessories,Logitechï¿½P710e Mobile Speakerphone,"617,976",3,"0,2","-7,7247"
251,251,CA-2016-145625,9/11/2016,9/17/2016,Standard Class,KC-16540,Kelly Collister,Consumer,United States,San Diego,...,92037,West,OFF-PA-10004569,Office Supplies,Paper,"Wirebound Message Books, Two 4 1/4"" x 5"" Forms...","7,61",1,0,"3,5767"
252,252,CA-2016-145625,9/11/2016,9/17/2016,Standard Class,KC-16540,Kelly Collister,Consumer,United States,San Diego,...,92037,West,TEC-AC-10003832,Technology,Accessories,Logitechï¿½P710e Mobile Speakerphone,"3347,37",13,0,"636,0003"
524,524,US-2016-139486,5/21/2016,5/23/2016,First Class,LH-17155,Logan Haushalter,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10003555,Technology,Phones,Motorola HK250 Universal Bluetooth Headset,"55,176",3,"0,2","-12,4146"
525,525,US-2016-139486,5/21/2016,5/23/2016,First Class,LH-17155,Logan Haushalter,Consumer,United States,Los Angeles,...,90032,West,TEC-AC-10003832,Technology,Accessories,Imationï¿½16GB Mini TravelDrive USB 2.0ï¿½Flash Drive,"66,26",2,0,"27,1666"
644,644,CA-2017-106103,6/10/2017,6/15/2017,Standard Class,SC-20305,Sean Christensen,Consumer,United States,Rochester Hills,...,48307,Central,TEC-AC-10003832,Technology,Accessories,Imationï¿½16GB Mini TravelDrive USB 2.0ï¿½Flash Drive,"132,52",4,0,"54,3332"

In [19]:
df1[df1["Order_ID"] == 'US-2017-100930']

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
231,232,US-2017-100930,4/7/2017,4/12/2017,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Tampa,...,33614,South,FUR-TA-10001705,Furniture,Tables,Bush Advantage Collection Round Conference Table,"233,86",2,"0,45","-102,048"
232,233,US-2017-100930,4/7/2017,4/12/2017,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Tampa,...,33614,South,FUR-TA-10003473,Furniture,Tables,Bretford Rectangular Conference Table Tops,"620,6145",3,"0,45","-248,2458"
233,234,US-2017-100930,4/7/2017,4/12/2017,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Tampa,...,33614,South,OFF-BI-10001679,Office Supplies,Binders,GBC Instant Index System for Binding Systems,"5,328",2,"0,7","-3,552"
234,235,US-2017-100930,4/7/2017,4/12/2017,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Tampa,...,33614,South,FUR-FU-10004017,Furniture,Furnishings,Tenex Contemporary Contur Chairmats for Low an...,"258,072",3,"0,2",0
235,236,US-2017-100930,4/7/2017,4/12/2017,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Tampa,...,33614,South,TEC-AC-10003832,Technology,Accessories,Logitechï¿½P710e Mobile Speakerphone,"617,976",3,"0,2","-7,7247"

In [27]:
result1 = df1.groupby("Product_ID").agg({"Quantity":"sum"}).rename(columns={"Quantity": "sum"}).sort_values(by="sum", ascending=False)

In [28]:
result1

                 sum
Product_ID
TEC-AC-10003832   75
OFF-PA-10004100    7
OFF-AP-10002287    7
OFF-ST-10003442    6
OFF-SU-10000432    6
TEC-PH-10000441    5
OFF-PA-10002137    5
OFF-AP-10003040    5
OFF-ST-10002554    5
OFF-SU-10000898    5
FUR-FU-10003731    4
TEC-PH-10003555    3
OFF-BI-10002432    3
OFF-PA-10003848    3
OFF-PA-10000809    3
OFF-ST-10000563    3
TEC-AC-10002637    3
OFF-AP-10004532    3
FUR-TA-10003473    3
TEC-MA-10003589    3
FUR-FU-10004017    3
FUR-FU-10002505    3
FUR-FU-10001290    3
TEC-AC-10001465    2
OFF-SU-10002537    2
TEC-AC-10002942    2
FUR-BO-10002824    2
OFF-LA-10000081    2
OFF-FA-10000611    2
OFF-BI-10001679    2
OFF-BI-10001116    2
OFF-AP-10003622    2
FUR-TA-10001705    2
FUR-FU-10001876    2
OFF-PA-10004569    1
FUR-BO-10004467    1
OFF-AR-10003183    1
OFF-PA-10000474    1

In [ ]:
result1 = df1.groupby("Product_ID").agg({"Quantity":"sum"}).rename(columns={"Quantity": "sum"}).sort_values(by="sum", ascending=False).head(2).reset_index().iloc[1]["Product_ID"]

In [ ]:
df1[df1["Product_ID"] == result1]